### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined     at module.exports

### ISSUE THREAD

**Issue by dmitriz** [angular/angular-hint#114]
I am getting this error when trying to run 
https://github.com/angular/angular-hint/blob/master/dist/hint.js
inside the browser. It is claimed that `module` in line 1054 is not defined.

Here is the exact error message:

Uncaught Error: [$injector:modulerr] Failed to instantiate module ngHintModules due to:
TypeError: Cannot read property 'name' of undefined
    at module.exports (http://localhost:8000/node_modules/angular-hint/dist/hint.js:1054:20)
    at http://localhost:8000/node_modules/angular-hint/dist/hint.js:1060:7
    at Array.forEach (native)
    at module.exports (http://localhost:8000/node_modules/angular-hint/dist/hint.js:1058:21)
    at http://localhost:8000/node_modules/angular-hint/dist/hint.js:1060:7
    at Array.forEach (native)
    at module.exports (http://localhost:8000/node_modules/angular-hint/dist/hint.js:1058:21)
    at http://localhost:8000/node_modules/angular-hint/dist/hint.js:1353:3
    at Object.invoke (http://localhost:8000/assets/angular.js:4203:17)
    at runInvokeQueue (http://localhost:8000/assets/angular.js:4109:35)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=ngHintModules&p1=T…keQueue%20(http%3A%2F%2Flocalhost%3A8000%2Fassets%2Fangular.js%3A4109%3A35)

**Comment by brettjacobson** [comment]
I have the same problem.  Does hint.js "require" requireJS or some other module loader, that our project doesn't have??

**Comment by SomeKittens** [comment]
@brettjacobson not the compiled version.

Can either of you post repo code?  Somehow it's passing undefined values.

**Comment by whisher** [comment]
I've got the same problem but only in
chrome !!! in firefox the app works fine.
Mint distro

**Comment by r20** [comment]
I noticed my Chrome debugging session all of a sudden hit this when I hadn't changed anything that I thought would cause it, and I wasn't using hint.js.  It turns out, it was from the AngularJS plugin in the debugger.  If I disable AngularJS debugging and only use the rest of Chrome's debugger I'm fine.

**Comment by onphenomenon** [comment]
disabling the plugin worked, thank goodness. couldn't find any changes in the diff that would have caused it.

**Comment by SomeKittens** [comment]
I can't reproduce this.

What version of Angular are you running this against?  Can you create a small example that demonstrates the problem?

**Comment by benzid-wael** [comment]
I have the same problem: My app was working well until this morning. If I deactivate the``Batarang`` extension, everything work as expected, once I activate it and refresh the page I got this error.

Did you have any idea how to fix it ?

**Comment by gibbitz** [comment]
Same issue here. I re-bowered my site last night to add more libraries and noticed the problem right afterwards. My versions and plugins are:
  * ui-router-extras 0.1.0
  * angular 1.4.8
  * angular-ui-router 0.2.15
  * angular-animate 1.4.8

Thought the versions of plugins and which are involved may be helpful for reproducing/figuring this out.

**Comment by btford** [comment]
There was a regression in v0.10.2. Can you all please make sure you're on
v0.10.4? I'll try and take a look today if people are still seeing this.

Thanks!

**Comment by SomeKittens** [comment]
You might need to do it manually (updates don't always all go out at once).

Hamburger menu -> More Tools -> Extensions

Then click the "Update Extensions Now" button:

<img width="915" alt="screen shot 2015-12-03 at 10 02 05 am" src="https://cloud.githubusercontent.com/assets/1616464/11569145/06b63ace-99a5-11e5-89f5-dd7b2099385b.png">

**Comment by benzid-wael** [comment]
I'm not sure if I was in v0.10.4 or not. I just reinstalled the extension and the error disappeared.

**Comment by SomeKittens** [comment]
Confirmed fix - thanks!

**Comment by brettjacobson** [comment]
I'm still getting this exception; i've uninstalled Chrome extensions, and I'm getting the exception in Internet Explorer, too.  When I debug, there is no "name" property on "module" (hence the exception).

angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module ngHintModules due to:
TypeError: Cannot read property 'name' of undefined
    at module.exports (http://localhost:8596/bower_components/angular-hint/dist/hint.js:1055:30)
    at http://localhost:8596/bower_components/angular-hint/dist/hint.js:1061:21
    at Array.forEach (native)
    at module.exports (http://localhost:8596/bower_components/angular-hint/dist/hint.js:1059:33)
    at http://localhost:8596/bower_components/angular-hint/dist/hint.js:1061:21
    at Array.forEach (native)
    at module.exports (http://localhost:8596/bower_components/angular-hint/dist/hint.js:1059:33)
    at http://localhost:8596/bower_components/angular-hint/dist/hint.js:1355:17
    at Object.invoke (http://localhost:8596/bower_components/angular/angular.js:4450:17)
    at runInvokeQueue (http://localhost:8596/bower_components/angular/angular.js:4356:35)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=ngHintModules&p1=Ty…F%2Flocalhost%3A8596%2Fbower_components%2Fangular%2Fangular.js%3A4356%3A35)

**Comment by SomeKittens** [comment]
How are you including angular-hint in your codebase?  If it's happening on Internet Explorer, that's not through Batarang.

**Comment by Mavlarn** [comment]
I disabled Batarang and this problem still exists.

**Comment by samuelt1** [comment]
I have the exact same problem

after disabling batarang the problem is resolved.
`
Failed to instantiate module ngHintModules due to:
TypeError: Cannot read property 'name' of undefined
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1060:20)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1066:7
    at Array.forEach (<anonymous>)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1064:21)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1360:5
    at Object.invoke (http://localhost:3000/lib/angular/js/angular.min.js:42:8)
    at d (http://localhost:3000/lib/angular/js/angular.min.js:39:481)
    at http://localhost:3000/lib/angular/js/angular.min.js:40:88
    at q (http://localhost:3000/lib/angular/js/angular.min.js:7:371)
    at g (http://localhost:3000/lib/angular/js/angular.min.js:39:382
`
