### ISSUE TITLE
When to deliver hint messages

### ISSUE THREAD

**Issue by ealtenho** [angular/angular-hint#29]
In the same vein as #27 of translating the hintLog pipeline into messages that the user can consume, there needs to be some specific time at which the messages are flushed. I believe the current TravisCI build https://travis-ci.org/angular/angular-hint/jobs/31192589 is failing because of the timing of when messages are flushed. These tests pass locally. However, there is some delay between when the messages are logged and when protractor looks at the DOM to read values.

**Comment by SomeKittens** [comment]
`angular.hint` is now an event emitter, so there isn't a `flush` anymore.  Consequently, we're not caching messages for consumers.  We may re-open this at a later date.
