### ISSUE TITLE
syntax in `package.json`

### ISSUE THREAD

**Issue by ealtenho** [angular/angular-hint#38]
@btford  I've looked up the definition of the `~` in npm install syntax, but I'm still confused about why I cannot automatically install the patch versions I have been working on using `npm install` at this point. 

From npm:
```
 version Must match version exactly
>version Must be greater than version
>=version etc
<version
<=version
~version "Approximately equivalent to version" See semver(7)
^version "Compatible with version" See semver(7)
```

And from semver:
```
~1.2.3 := >=1.2.3-0 <1.3.0-0 "Reasonably close to 1.2.3". When using tilde operators, prerelease versions are supported as well, but a prerelease of the next significant digit will NOT be satisfactory, so 1.3.0-beta will not satisfy ~1.2.3.
```

Are pre-releases with 0.x.x different than betas?
I'm concerned that only I am working with updated versions of most of the submodules since installation seems to require explicit `npm install angular-hint-module-name@x.x.x` syntax.

**Comment by SomeKittens** [comment]
(this is an npm issue, closing)
