### ISSUE TITLE
Do you have a packaged version

### ISSUE THREAD

**Issue by shprink** [angular/angular-hint#57]
Hi,

Do you have a packaged repo just to get the necessary code not all the dev dependencies (npm install angular-hint > 200Mb)

My project doubled in size just with this dependency.

Cheers,
Shprink

**Comment by hgoebl** [comment]
+1
For me it added 586 MB for just 68 kB in dist/

**Comment by btford** [comment]
>  586 MB

That's huge! If you use a modern version of npm (`npm install -g npm`) you should have some of the hefty dependencies de-duped.

I'm going to push a bundle today that includes the dist folder.

**Comment by btford** [comment]
Just published `v0.3.3`, which includes the dist folder: https://github.com/angular/angular-hint/blob/master/dist/hint.js

Closing, but let me know if there's anything else that should be done to make angular-hint easy to consume.
