### ISSUE TITLE
refactor: move sub-modules into this repo

### ISSUE THREAD

**Issue by btford** [angular/angular-hint#64]
This was originally split into separate modules because it made implementing them simpler.

However, having each of these in separate repos has made it harder to test this module as a whole. Thus, I want to move the code for all modules here.

This will make it easier to reason about the code, and also help improve the performance, especially in places where angular-hint monkey-patches existing APIs.

I still want to publish individual modules (so you can just `npm install angular-hint-dom`, for instance).

**Comment by erwinmombay** [comment]
@btford would love to help out with this to move forward the batarang improvements. any guidance on how to bring the modules back in while still being able to publish individual modules? (only thing that pops in my head is how lodash does it with its builds)

**Comment by SomeKittens** [comment]
Done!  Thanks @welbornio

**Comment by safwathannadeif** [comment]
aaaa
