### ISSUE TITLE
Inaccurate occurrences of "multiple modules being created" error

### ISSUE THREAD

**Issue by mattlavallee** [angular/angular-hint#67]
When including angular-hint in my project, it logs that several of my modules are being created multiple times.
Searching the code base (fairly small at this point) for the module name, there is only one instance of using angular.module() with the setter parameter.  Setting a breakpoint on my webpage, this line is also only hit once.

I'm attempting to figure out why angular-hint thinks it's being created more than once.

Any suggestions you can offer would be very helpful

**Comment by mattlavallee** [comment]
Debugging angular-hint-modules, I found that the first occurrence of a "duplicate module creation" is coming from this line
![image](https://cloud.githubusercontent.com/assets/1207606/6042440/c8a99568-ac52-11e4-91d5-42b2e9b24a64.png)

My entire call stack at this point is:
![image](https://cloud.githubusercontent.com/assets/1207606/6042444/de908652-ac52-11e4-8ed2-00bf6b1f2188.png)

The second occurrence is happening from this line:
![image](https://cloud.githubusercontent.com/assets/1207606/6042464/0c83268c-ac53-11e4-9b91-7c9faf604a05.png)

Again, a very simple call stack:
![image](https://cloud.githubusercontent.com/assets/1207606/6042467/1865b078-ac53-11e4-8c07-0d4e4ba1284b.png)


I believe that this is a bug and is registering a "Multiple modules with name <name> are being create" message in error

**Comment by mattlavallee** [comment]
Upon further debugging, it looks like the problem can be solved with 2 lines in angular-hint-modules by checking the arguments for more than one parameter (indicating it's a module setter rather than a getter)
```
angular.module = function(name, requiresOriginal) {
  var module = originalAngularModule.apply(this, arguments),
      name = module.name;

  module.requiresOriginal = requiresOriginal;
  modules[name] = module;
  hasNameSpace(module);
  var modToCheck = getModule(name, true);
  var modlIsSetter = arguments.length > 1; //check arguments to determine if angular.module() is called as a setter or a getter

  if(modToCheck && modToCheck.requiresOriginal !== module.requiresOriginal && modIsSetter) { //add new modIsSetter boolean to the conditional
    if(!modData.createdMulti[name]) {
      modData.createdMulti[name] = [getModule(name,true)];
    }
    modData.createdMulti[name].push(module);
  }
  modData.createdModules[name] = module;
  return module;
};
```

Please let me know if you would like me to submit this as a pull request

**Comment by SomeKittens** [comment]
@mattlavallee wow, nice debugging.  Thanks for finding/reporting the bug and we'd love a PR!

**Comment by SomeKittens** [comment]
Matt's PR https://github.com/angular/angular-hint/pull/86 fixed this.
