### ISSUE TITLE
refactor: import angular-hint-modules

### ISSUE THREAD

**Issue by btford** [angular/angular-hint#69]
https://github.com/angular/angular-hint/blob/refactor-all-the-things/hint.js#L12

rename this: https://github.com/angular/angular-hint/blob/refactor-all-the-things/src/modules/modules.xjs

import these files: https://github.com/angular/angular-hint/blob/refactor-all-the-things/src/modules/modules.xjs#L3-L8

**Comment by SomeKittens** [comment]
Fixed in #70
