### ISSUE TITLE
Warn about modularity issues

### ISSUE THREAD

**Issue by kentcdodds** [angular/angular-hint#74]
[moxee](https://github.com/alianza-dev/moxee) is a library that I'm currently working on that helps applications be modular. See the repo for more information about what it does and why. Right now I'm working on making it not depend on a testing framework and then I realized that a better place for this would be in ng-hint. Runtime warnings about using injectables that are not part of a module or its dependencies would be awesome to have.

**Comment by welbornio** [comment]
I'm taking a peek. Thanks kent

**Comment by SomeKittens** [comment]
Implementing this would be a good candidate for the module system.
