### ISSUE TITLE
Angular hints events doesn't work

### ISSUE THREAD

**Issue by DennisNerush** [angular/angular-hint#75]
I've used the code sample from the docs:
var myApp = angular.module('myApp', []);

myApp.controller('myCtrl', ['$scope', function ($scope) {
    $scope.count = 0;
    $scope.divideValue;
    $scope.increment = function () {
        ++$scope.count
    };
    $scope.dividend = function () {
        return Math.random() * 20 + 20
    };
    $scope.divisor = function () {
        return Math.random() * 10 + 1
    };
}]);

div ng-controller="myCtrl"
        a ng-click="increments">Count!</a>
        a ng-click="divideVal = dividend() / divide()">Count!</a>
    /div>

There is no hint warning in the controller.

**Comment by SomeKittens** [comment]
(Jumped the gun on the above PR, it does not fully fix this issue, as `controllers.js` uses `log`, not `emit`.)  Sorry about that!

**Comment by DennisNerush** [comment]
So does it work now?

**Comment by SomeKittens** [comment]
@DennisNerush I'll be meeting with the rest of the team later today and will ask about this.  Hopefully we'll have a timeline for getting everything together.  Apologies about the wait.

**Comment by DennisNerush** [comment]
Thank you. I'm waiting for the results.


  [image: photo]
*Dennis Nerush*
 p:+972 -524713667 | e:nerush.dennis@gmail.com | w:
http://dennis-nerush.blogspot.co.il
 <http://www.facebook.com/dennis.nerush>
<http://www.linkedin.com/profile/view?id=161938167>
<http://twitter.com/DennisNerush>
    Latest Tweet: <https://twitter.com/DennisNerush> Improving Angular.js
performance using One Time Binding - http://t.co/JSbJy8V9D8 Read More
<https://twitter.com/DennisNerush/statuses/586271516595253248>
  Get a signature like this:
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

**Comment by SomeKittens** [comment]
@DennisNerush Can you see if latest master fixes this?  If not, create a Plunker that reproduces the problem and we'll be right on it.  Thanks again for helping out!
