### ISSUE TITLE
package.json version doesn't match latest release verion

### ISSUE THREAD

**Issue by ilanbiala** [angular/angular-hint#78]
`package.json` has `0.0.0`, but the latest release is tagged `0.1.0`.

**Comment by erwinmombay** [comment]
created PR for this https://github.com/angular/angular-hint/pull/79

**Comment by SomeKittens** [comment]
@erwinmombay We should probably go to `0.2.0` for this, given the major change in how `hint.emit` works

**Comment by erwinmombay** [comment]
@SomeKittens got it. anywhere else the version needs to be bumped?

**Comment by SomeKittens** [comment]
I've bumped it in my branch of Batarang but haven't pushed that yet

**Comment by SomeKittens** [comment]
Fixed in #79
