### ISSUE TITLE
angular.hint.onMessage is empty function

### ISSUE THREAD

**Issue by wkwiatek** [angular/angular-hint#81]
I couldn't make angular-hint working when using as browserify package as well as built version. The problem I met is that there is an empty function which I suppose is meant to work as logger. It's in this particular line: https://github.com/angular/angular-hint/blob/master/src/modules/log.js#L49

I've tried to run one of your examples with no success. I've added generated _hint.js_ file to this plunker: http://plnkr.co/edit/qxaz82gNQjiPyIVt2v9g

Also the dependencies seems to be a little bit outdated themselves. It may be a problem with node 0.12 which I use.

**Comment by erwinmombay** [comment]
hey @wkwiatek thanks for reporting. you don't happen to have a log of any errors you saw did you?

**Comment by SomeKittens** [comment]
Good find - we forgot to pull this out earlier.

`angular.hint` is now an EventEmitter, so you can add event listeners to that.  We'll have to figure out what to do with the logging.

**Comment by wkwiatek** [comment]
Hi guys. Thanks for your reply. 

@SomeKittens I changed the version in my project to your fixed branch and it seems to emit events now but I can't find any place where they're handled. Am I wrong or is there any other way to see messages from `angular-hint` in that version?

**Comment by SomeKittens** [comment]
@wkwiatek Glad to see the update works for you.  Currently, there isn't a way to get angular-hint to do this for you (I've opened https://github.com/angular/angular-hint/issues/85 to track this).  A quick workaround would be to enter `angular.hint.onAny(console.log.bind(console))` into the console.
