### ISSUE TITLE
Bootstrapping fails on Angular home page

### ISSUE THREAD

**Issue by SomeKittens** [angular/angular-hint#88]
Go to https://angularjs.org/, note the new error: `Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=ngLocal.us&p1=Type…nsion%3A%2F%2Fgmenniinnbhdnjhbpbeokoobgfnjlhlm%2Fdist%2Fhint.js%3A513%3A11)`

This is due to us poorly overriding Angular bootstrapping, specifically manual bootstrapping:

```
angular.module('ngLocal.us', [])._configBlocks.push(angular.module('ngLocale')._configBlocks[0]);
angular.bootstrap(document, ['ngRoute', 'homepage', 'ngLocal.us']);
```

**Comment by SomeKittens** [comment]
Looks like we're stripping away the config block of `ngLocale`, which means that `ngLocale.us` has a configBlock length of 1, but the item is `undefined`.

**Comment by SomeKittens** [comment]
Some stream of consciousness from my last debug session:
It's not stripped away.  The config block of `ngLocale` is being executed AFTER the code in question in the top post?

Or perhaps we're overriding `angular.module` so the third parameter isn't getting through?  We're passing `arguments` through though.  (The third argument is passed through - the question is to what?)

perhaps there's two modules dancing around?

**Comment by rev087** [comment]
According to [this comment](https://github.com/angular/angularjs-batarang/blob/master/loader.js#L373)  in line 373 of `loader.js`, all config blogs are being pushed to the end of the invokeQueue by the extension.

This conflicts with the code used in angularjs.org that directly manipulates config blocks via `[module]._configBlocks`.

In particular, I believe `_configBlocks[0]` would be undefined at that time (as `loader.js` is "deferring" it's registration).

Removing this config blog manipulation would fix this particular issue, but it would probably cause a regression in ng-hint, so it's necessary to track down why it was added in the first place.

[git blame](https://github.com/angular/angularjs-batarang/commit/6a0ae94f4df7f5dea3a10874f6f9be9603e353cc) points to the [relevant issue](https://github.com/angular/angular-hint/issues/39).

**Comment by rev087** [comment]
I'm still trying to make sense of the original issue, but skimming over the comments "double bootstrap" and "ngLocale" pop up in there. Deja vu!

Manipulating the invokeQueue in the extension should be avoided imho, it's a bit too intrusive in the context of a browser extension (granted, debugging tools are unavoidably intrusive, but we should strive to avoid that whenever possible).

That being said, that piece of code from the angularjs.org is another issue in itself (imho again, accessing a "private API" in the context of an Angular application feels just wrong).

**Comment by rev087** [comment]
This is the line in the angularjs.org repo: [index.html:972](https://github.com/angular/angularjs.org/blob/master/src/index.html#L972)

Apparently, before Angular 1.2 `_configBlocks` were stored in `[module]._invokeQueue` along with the other providers.

The earliest commit I could track down that includes this is from [April 2, 2012](https://github.com/angular/angularjs.org/commit/b41508e22068f8517657cf3c76fa5650e07edf61#diff-eacf331f0ffc35d4b482f1d15a887d3bR699), but unfortunately the commit message doesn't give me any insight into why this was necessary (I can't seem to figure out what "Zippy" is)

**Comment by gkalpak** [comment]
Fixed in https://github.com/angular/batarang/pull/311/commits/1e5bd106f6add6449baf15938667d8bc0db40b86.
