### ISSUE TITLE
dist angular-hint.js file to be used without requirejs?

### ISSUE THREAD

**Issue by leschirmeur** [angular/angular-hint#91]
Is there a dist file available which could be used without requirejs? We are not using requirejs in our project but nevertheless would like to use angular-hint.

**Comment by SomeKittens** [comment]
This is actually compiled with `browserify`.  You should be able to include `dist/hint.js` without needing any other external library (other than Angular, of course).

**Comment by alberto** [comment]
The npm package does not include a dist folder.

**Comment by btford** [comment]
That's a valid concern.

**Comment by btford** [comment]
I just landed v0.3.3 with the dist included: https://github.com/angular/angular-hint/blob/master/dist/hint.js

I'm going to close this, but let me know if there's anything else I can do to make Angular Hint easier to use.

Thanks!

**Comment by alberto** [comment]
The latest package on npm is still 0.3.2. I'm not sure if you have to do anything to publish the new version there or if I should just wait until it shows up.

**Comment by alberto** [comment]
Mmm, I tried to get it directly from github using "angular/angular-hint" on my package.json, but I still couldn't get the dist folder. I guess it's because it's still excluded in .gitignore?

**Comment by dmitriz** [comment]
The dist folder is still not installed with npm. Would be nice to have it there.
