### ISSUE TITLE
Reconsidering bower?

### ISSUE THREAD

**Issue by wjzhou** [angular/angular-hint#93]
I know there are similar closed issues. But, could you reconsider the case and provide a official bower package?
Thank you.

The problem is we are using Visual Studio 2015 to access the bower/npm package. The npm package just don't work under this setup. The node dependence will exceed the windows 260 PATH limit and crash the visual studio.

Current, I have to compile the angular-hint on my computer and then check-in the distribution file.

It will be really helpful if you can provide a official one. (There are actually a bower package called angular-hint2 that is basically the v0.1.0 + dist folder. However, I can't trust (not personal) that 3-rd package in my project.

**Comment by SomeKittens** [comment]
I'm going to leave this open as there's obviously demand for a bower package.

There are many higher-priority things to be done here, so don't expect it soon.

**Comment by welbornio** [comment]
I can work on this.

**Comment by welbornio** [comment]
@btford Would it be possible to get a separate repo for the angular-hint-bower package?

**Comment by SomeKittens** [comment]
You can now use https://github.com/welbornio/angular-hint-bower
